export const DATE_FORMAT = 'yyyy-MM-dd';
export const WEEK_DAY_NAMES = ['sun', 'mon', 'tue', 'wed', 'thu', 'fri', 'sat'];
export const MONTHS_NAMES = ['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec'];
export const DAY_MONTH_NAMES = {
  en: {
    month:{
      short: {
        jan: 'jan',
        feb: 'feb',
        mar: 'mar',
        apr: 'apr',
        may: 'may',
        jun: 'jun',
        jul: 'jul',
        aug: 'aug',
        sep: 'sep',
        oct: 'oct',
        nov: 'nov',
        dec: 'dec',
      },
      long: {
        jan: 'january',
        feb: 'february',
        mar: 'march',
        apr: 'april',
        may: 'may',
        jun: 'jun',
        jul: 'july',
        aug: 'august',
        sep: 'september',
        oct: 'october',
        nov: 'november',
        dec: 'december',
      },
      longer: {
        jan: 'January',
        feb: 'February',
        mar: 'March',
        apr: 'April',
        may: 'May',
        jun: 'Jun',
        jul: 'July',
        aug: 'August',
        sep: 'September',
        oct: 'October',
        nov: 'November',
        dec: 'December',
      },
    },
    day: {
      sun: 'Su',
      mon: 'Mo',
      tue: 'Tu',
      wed: 'We',
      thu: 'Th',
      fri: 'Fr',
      sat: 'Sa',
    },
  },
  uk: {
    month:{
      short: {
        jan: 'сiч',
        feb: 'лют',
        mar: 'бер',
        apr: 'квi',
        may: 'тра',
        jun: 'чер',
        jul: 'лип',
        aug: 'сер',
        sep: 'вер',
        oct: 'жов',
        nov: 'лис',
        dec: 'гру',
      },
      long: {
        jan: 'ciчня',
        feb: 'лютого',
        mar: 'березня',
        apr: 'квiтня',
        may: 'травня',
        jun: 'червня',
        jul: 'липня',
        aug: 'серпня',
        sep: 'вересня',
        oct: 'жовтня',
        nov: 'листопада',
        dec: 'грудня',
      },
      longer: {
        jan: 'Сiчень',
        feb: 'Лютий',
        mar: 'Березень',
        apr: 'Квiтень',
        may: 'Травень',
        jun: 'Червень',
        jul: 'Липень',
        aug: 'Серпень',
        sep: 'Вересень',
        oct: 'Жовтень',
        nov: 'Листопад',
        dec: 'Грудень',
      },
    },
    day: {
      sun: 'Нд',
      mon: 'Пн',
      tue: 'Вт',
      wed: 'Ср',
      thu: 'Чт',
      fri: 'Пт',
      sat: 'Сб',
    },
  },
  ru: {
    month:{
      short: {
        jan: 'янв',
        feb: 'фев',
        mar: 'мар',
        apr: 'апр',
        may: 'май',
        jun: 'июн',
        jul: 'июл',
        aug: 'авг',
        sep: 'сен',
        oct: 'окт',
        nov: 'ноя',
        dec: 'дек',
      },
      long: {
        jan: 'января',
        feb: 'февраля',
        mar: 'марта',
        apr: 'апреля',
        may: 'мая',
        jun: 'июня',
        jul: 'июля',
        aug: 'августа',
        sep: 'сентября',
        oct: 'октября',
        nov: 'ноября',
        dec: 'декабря',
      },
      longer: {
        jan: 'Январь',
        feb: 'Февраль',
        mar: 'Март',
        apr: 'Апрель',
        may: 'Май',
        jun: 'Июнь',
        jul: 'Июль',
        aug: 'Август',
        sep: 'Сентябрь',
        oct: 'Октябрь',
        nov: 'Ноябрь',
        dec: 'Декабрь',
      },
    },
    day: {
      sun: 'Вс',
      mon: 'Пн',
      tue: 'Вт',
      wed: 'Ср',
      thu: 'Чт',
      fri: 'Пт',
      sat: 'Сб',
    },
  },
};
